# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AxivityNumUnpack <- function(pack) {
    .Call(`_GGIRread_AxivityNumUnpack`, pack)
}

GENEActivReader <- function(filename, start = 0L, end = 0L, progress_bar = FALSE) {
    .Call(`_GGIRread_GENEActivReader`, filename, start, end, progress_bar)
}

resample <- function(raw, rawTime, time, stop, type = 1L) {
    .Call(`_GGIRread_resample`, raw, rawTime, time, stop, type)
}

