# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numUnpack <- function(pack) {
    .Call(`_GGIRread_numUnpack`, pack)
}

resample <- function(raw, rawTime, time, stop, type = 1L) {
    .Call(`_GGIRread_resample`, raw, rawTime, time, stop, type)
}

